# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            hispn.com
tagline:          'Hispanos'
description:      "Agregador de datos paises hispanos."
url:              https://hispn.com/
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Daniel Victorino Bremont'
  url:            https://hispn.com/

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/DanielBremont/hispn.github.io
